### ISSUE TITLE
Project Update with ASK CLI Deployment Support

### ISSUE THREAD

**Issue by jsetton** [tartanguru/alexa-assistant#105]
I made some extensive changes including adding support for Node.js 14.x and the [ASK CLI](https://developer.amazon.com/en-US/docs/alexa/smapi/quick-start-alexa-skills-kit-command-line-interface.html) deployment tools. This should help streamline the setup of the skill on the Amazon end. The deployment script can either build the Lambda dependencies locally if docker is installed on your machine, or use the latest Lambda release package from my repository. It should also work on either Linux or Windows machines.

Other changes includes support for device location using the Alexa device address of the requested Echo device. This requires to activate the skill permission and the use of the Google Maps Geocoding API to convert the received postal code and country into geocoordinates format required by the Google Assistant API.

https://github.com/jsetton/alexa-assistant

**Comment by scofield8610** [comment]
Hi jsetton, i followe your Deployment Steps, but at Point "1) Deploy the skill and the lambda function in one step" i don´t know waht you mean. Is it better to use docker local or amazon ASK CLI? I tried both, but its not easy to use...

**Comment by jsetton** [comment]
> Deploy the skill and the lambda function in one step

As indicated in that step, you need to run the ASK CLI command `ask deploy` assuming you went through the pre-requisites to install and initialize ASK CLI. As far as Docker requirement, it is optional. So I would say don't bother with it.

**Comment by scofield8610** [comment]
Ok, so I should use ASK CLI. Is there anywhere an manual for beginners? I didn´t unterstand The ASK CLI in detail - so, where can I give the command "ask deploy"?

**Comment by jsetton** [comment]
The link to the ASK CLI documentation is in the pre-requities steps. You can also find tutorials online.

**Comment by scofield8610** [comment]
I understand so far, at the last step **ask deploy** is in the end an error:

Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

==================== Deploy Skill Metadata ====================
Skill package deployed successfully.
Skill ID: amzn1.ask.skill.c8ec44ad-a673-40c4-aae5-b1c9e488bb8e

==================== Build Skill Code ====================
In C:\users\christian\appdata\roaming\npm\alexa-assistant\hooks\build.ps1:130 Zeichen:41
+         $DepCmd = "docker run --rm -v `"$pwd:/src`" -w /src `"$Docker ...
+                                         ~~~~~
Ungültiger Variablenverweis. Nach ":" folgte kein Zeichen, das für einen Variablennamen gültig ist. Verwenden Sie ggf. "${}", um den Namen zu begrenzen.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidVariableReferenceWithDrive

Skill code built successfully.
Code for region default built to C:\users\christian\appdata\roaming\npm\alexa-assistant\.ask\lambda\build.zip successfully with build flow CustomBuildFlow.

==================== Deploy Skill Infrastructure ====================
  × Deploy Alexa skill infrastructure for region "default"
    → ENOENT: no such file or directory, stat 'C:\users\christian\appdata\roaming\npm\alexa-assistant\.ask\lambda\build.zip'
[Error]: CliError: ENOENT: no such file or directory, stat 'C:\users\christian\appdata\roaming\npm\alexa-assistant\.ask\lambda\build.zip'

**Comment by scofield8610** [comment]
The \build.zip doesn´t exist in the directory

**Comment by scofield8610** [comment]
It seems, as this error-amassage will be no problem.
How can i test, if alexa use bing or google for my ask?

**Comment by scofield8610** [comment]
Now i added the Language German and execute **ask deploy** again.
But in the Alexa-account, under skills, is the name of the Google Assistant now: please change, and there is no logo.
Can u help me for this?

**Comment by scofield8610** [comment]
Okay, logo and the rest description is now also in german available. But if i ask:
Alexa, frag google ... > she says: Entschuldigung, ich habe gerade Schwierigkeiten, versuche es bitte später noch einmal.

Is this an local temporay problem or a problem with the script?

**Comment by jsetton** [comment]
> Build Skill Code
In C:\users\XXX\appdata\roaming\npm\alexa-assistant\hooks\build.ps1:130 Zeichen:41
$DepCmd = "docker run --rm -v "$pwd:/src" -w /src `"$Docker ...
Ungültiger Variablenverweis. Nach ":" folgte kein Zeichen, das für einen Variablennamen gültig ist. Verwenden Sie ggf. "${}", um den Namen zu begrenzen.
CategoryInfo : ParserError: (:) [], ParseException
FullyQualifiedErrorId : InvalidVariableReferenceWithDrive

There was a bug with the Windows build script that I just fixed. The skill code wasn't actually getting deployed even it stated the opposite. You should use the latest version of my repository and run `ask deploy` again.

> Okay, logo and the rest description is now also in german available. But if i ask:
Alexa, frag google ... > she says: Entschuldigung, ich habe gerade Schwierigkeiten, versuche es bitte später noch einmal.

The error is most likely due to the skill function not currently deployed.

**Comment by scofield8610** [comment]
Now, with the actually build script (I updated the build.ps1), there are the following errors:

==================== Build Skill Code ====================
docker : error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file
specified.
In Zeile:1 Zeichen:1
+ docker version; $Running=$?
+ CategoryInfo          : NotSpecified: (error during co...file specified.:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError

node:child_process:903
    throw err;
    ^

Error: Command failed: PowerShell.exe -Command "& {& 'C:\users\christian\appdata\roaming\npm\alexa-assistant\hooks\build.ps1' 'C:\users\christian\appdata\roaming\npm\alexa-assistant\.ask\lambda\build.zip' $False }"
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at CustomBuildFlow.execCommand (C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\lib\builtins\build-flows\abstract-build-flow.js:79:18)
    at CustomBuildFlow.execute (C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\lib\builtins\build-flows\custom.js:45:10)
    at CodeBuilder.execute (C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\lib\controllers\skill-code-controller\code-builder.js:45:13)
    at C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\lib\controllers\skill-code-controller\index.js:39:19
    at C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\node_modules\async\dist\async.js:3110:16
    at eachOfArrayLike (C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\node_modules\async\dist\async.js:1069:9)
    at eachOf (C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\node_modules\async\dist\async.js:1117:5)
    at Object.eachLimit (C:\Users\Christian\AppData\Roaming\npm\node_modules\ask-cli\node_modules\async\dist\async.js:3172:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13968,
  stdout: null,
  stderr: null
}

**Comment by scofield8610** [comment]
> The error is most likely due to the skill function not currently deployed.
From what it will depend, if the skill is currently deployed?

**Comment by jsetton** [comment]
> docker : error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.

It looks like you have Docker installed in your environment. Anyway, I added a update to catch exceptions to the Windows build script. Give it a try with the latest version of my repository.

**Comment by scofield8610** [comment]
Now, there is another error :(

==================== Build Skill Code ====================
& : Die Datei "C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1" kann nicht geladen werden. Die
Datei "C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1" ist nicht digital signiert. Sie können
dieses Skript im aktuellen System nicht ausführen. Weitere Informationen zum Ausführen von Skripts und Festlegen der
Ausführungsrichtlinie erhalten Sie unter "about_Execution_Policies" (https:/go.microsoft.com/fwlink/?LinkID=135170)..
In Zeile:1 Zeichen:6
+ & {& 'C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build. ...
+
+ CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
+ FullyQualifiedErrorId : UnauthorizedAccess
Skill code built successfully.
Code for region default built to C:\users\christian\desktop\jsetton\alexa-assistant\.ask\lambda\build.zip successfully with build flow CustomBuildFlow.

==================== Deploy Skill Infrastructure ====================
  × Deploy Alexa skill infrastructure for region "default"
    → ENOENT: no such file or directory, stat 'C:\users\christian\desktop\jsetton\alexa-assistant\.ask\lambda\build.zip
'
[Error]: CliError: ENOENT: no such file or directory, stat 'C:\users\christian\desktop\jsetton\alexa-assistant\.ask\lambda\build.zip'

**Comment by jsetton** [comment]
> Now, there is another error :(

`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`

**Comment by scofield8610** [comment]
This command was run successfully, but have make no changes.
I tried also with 
`-Scope LocalMachine`
, but theres the same Error

**Comment by scofield8610** [comment]
With `Get-ExecutionPolicy -List` this is the result:

Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned

**Comment by jsetton** [comment]
At this point, I don't know much more. Based on the link in the error, this indicates your PowerShell execution policy isn't allowing the build script to be executed. This has to do with your environment and not the script itself.

**Comment by scofield8610** [comment]
Also i did this changes:
`Set-ExecutionPolicy -ExecutionPolicy unrestricted -Scope CurrentUser`

The Log is:

==================== Build Skill Code ====================

Sicherheitswarnung
Führen Sie ausschließlich vertrauenswürdige Skripts aus. Skripts aus dem Internet können zwar nützlich sein, stellen jedoch auch eine potenzielle Gefahr für Ihren Computer dar. Wenn Sie diesem Skript vertrauen, lassen Sie mit dem Cmdlet "Unblock-File" die Ausführung des
 Skripts ohne die Warnmeldung zu. Möchten Sie "C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1" ausführen?
[N] Nicht ausführen  [M] Einmal ausführen  [H] Anhalten  [?] Hilfe (Standard ist "N"): M
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:219 Zeichen:126
+ ... etails px-3 px-md-4 px-lg-5 flex-wrap flex-md-nowrap" role="banner" >
+
Dateispezifikation nach dem Umleitungsoperator fehlt.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:236 Zeichen:158
+ ... ent="true" class="Header-link js-details-target btn-link">  <svg aria ...
+
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:239 Zeichen:14
+ </button>    </div>
+
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:488 Zeichen:27
+  data-hydro-click="{&quot;event_type&quot;:&quot;analytics.eve ...
+ 
Unerwartetes Token "{" in Ausdruck oder Anweisung.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:488 Zeichen:44
+ data-hydro-click="{&quot;event_type&quot;:&quot;analytics.eve ...
+
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:488 Zeichen:51
+ data-hydro-click="{&quot;event_type&quot;:&quot;analytics.eve ...
+
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:488 Zeichen:72
+ ... a-hydro-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&q ...
+
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:488 Zeichen:79
+ ... o-click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;pa ...
+ 
Ausdruck fehlt nach dem unären Operator ",".
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:488 Zeichen:79
+ ... -click="{&quot;event_type&quot;:&quot;analytics.event&quot;,&quot;pay ...
+ 
Unerwartetes Token "&" in Ausdruck oder Anweisung.
In C:\users\christian\desktop\jsetton\alexa-assistant\hooks\build.ps1:488 Zeichen:92
+ ... t;event_type&quot;:&quot;analytics.event&quot;,&quot;payload&quot;:{& ...
+
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
Es wurden nicht alle Analysefehler berichtet. Korrigieren Sie die berichteten Fehler, und versuchen Sie es erneut.
+ CategoryInfo          : ParserError: (:) [], ParseException
+ FullyQualifiedErrorId : MissingFileSpecification

Skill code built successfully.
Code for region default built to C:\users\christian\desktop\jsetton\alexa-assistant\.ask\lambda\build.zip successfully with build flow CustomBuildFlow.

==================== Deploy Skill Infrastructure ====================
  × Deploy Alexa skill infrastructure for region "default"
    → ENOENT: no such file or directory, stat 'C:\users\christian\desktop\jsetton\alexa-assistant\.ask\lambda\build.zip'
[Error]: CliError: ENOENT: no such file or directory, stat 'C:\users\christian\desktop\jsetton\alexa-assistant\.ask\lambda\build.zip'

**Comment by scofield8610** [comment]
Now it seems like a formatting error in build.ps1, and not an restriction-problem!?

**Comment by jsetton** [comment]
> Now it seems like a formatting error in build.ps1

It looks like some HTML code is present in the file. How are you getting the latest version of my repository?

**Comment by scofield8610** [comment]
Link: 
https://github.com/jsetton/alexa-assistant

Click on Code (right corner) --> Download ZIP

**Comment by scofield8610** [comment]
Stop, i downloaded it again.
Now, the Build Skill Code have no errors.

Just the Deploy Skill Infrastructure says:

==================== Deploy Skill Infrastructure ====================
  × Deploy Alexa skill infrastructure for region "default"
[Error]: CliError: The CloudFormation deploy failed for Alexa region "default": The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by scofield8610** [comment]
In my AWS Console is the region set to Europa (Irland), this was the description from tartanguru

**Comment by scofield8610** [comment]
An the Developer Console has at the Endpoint no option choose:
![Endpoint](https://user-images.githubusercontent.com/57181175/146985570-6af1c16a-a2db-4c27-8bb3-b16224140b50.jpg)

**Comment by jsetton** [comment]
> [Error]: CliError: The CloudFormation deploy failed for Alexa region "default": The request signature we calculated does not match the signature you provided. Check your key and signing method.

The error means that the AWS Access Key ID and Secret Access Token credentials you provided during the ASK CLI initialization process are not valid. If you don't know what this means, there are some online tutorial that explains how to create these. You will need to re-initialize your ASK CLI configuration when you generated the access key.

**Comment by scofield8610** [comment]
Think ive nearly finished. Now the credentials are right but in AWS CloudFormation is continuous a rollback.
In ASK is the error:
[Error]: CliError: The CloudFormation deploy failed for Alexa region "default": S3Bucket[AWS::S3::Bucket]  CREATE_FAILED (Resource creation cancelled)
![S3](https://user-images.githubusercontent.com/57181175/146994170-5b9e0121-bea3-4568-aa82-589266adc2b5.jpg)


And in CloudFormation ist the following protocol:

**Comment by jsetton** [comment]
Did you go over the prerequisites if you are upgrading from v2?

**Comment by scofield8610** [comment]
Yeah, and all Stacks, S3 Buckets and lambdas are deleted, the developer console has no Skills

**Comment by scofield8610** [comment]
There is also been created a new Skill-ID, but there are the same errors

**Comment by scofield8610** [comment]
Yeah, now the Skill is enabled successfully!
Thank you so much for your patience and help!!!
If I say to Alexa: Frag Google she speak on english with me, can I change the Language to german?
In `ask-resources.json` I set eu-west-1 an in the directory interactionModels > custom ist just `de-DE.json`

**Comment by scofield8610** [comment]
Here is the CloudWatch protocol, maybe you can see the cause?
![protocol](https://user-images.githubusercontent.com/57181175/147004032-6fe025ed-2dd1-4d68-a243-9d33f546e2a8.jpg)

**Comment by jsetton** [comment]
I added support for localization. You will need to update your setup using the latest version of my repository. Make sure to copy over the `.ask` folder in order for ASK CLI to update your existing resources otherwise it will try to create new ones. The prerequisite step to add your specific skill locale is now longer needed since all supported skill locales are already included.

**Comment by scofield8610** [comment]
Yes, al languages are now in the package and Alexa speak with me on german. But theres now another error message, if i ask something she says:
Beim Registrieren des Gerätemodells bei der Google API ist ein Fehler aufgetreten.

FYI: I tried with echo dot 3 and echo dot 4

This is the new protocol:
![protocol](https://user-images.githubusercontent.com/57181175/147054044-8c39e3ed-42d1-46c0-9de8-5a140a71d531.jpg)

**Comment by jsetton** [comment]
Did you copy over your `ask-resources.json`? Your Google Project ID is most likely not defined.

**Comment by scofield8610** [comment]
Right, now there are two errors, have I really to enable the Billing on Google Cloud Project?

1) error_message: 'You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started',
      results: [],
      status: 'REQUEST_DENIED'

2)     "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak>Fehler beim Abrufen der Geocode-Koordinaten von Google Maps.</speak>"

**Comment by jsetton** [comment]
Both are related. You have to provide a credit card similar to AWS. Your usage will most likely never incur any charges.

https://github.com/tartanguru/alexa-assistant#why-do-i-need-a-credit-card

**Comment by scofield8610** [comment]
Ok, billing is enabled, but theres just another error:

2021-12-22T08:23:13.258Z	d52c6197-b998-4a1c-a443-f6cf32a3f7e1	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "write after end",
    "code": "ERR_STREAM_WRITE_AFTER_END",
    "stack": [
        "Error [ERR_STREAM_WRITE_AFTER_END]: write after end",
        "    at new NodeError (internal/errors.js:322:7)",
        "    at WriteStream.Writable.write (internal/streams/writable.js:292:11)",
        "    at Encoder.ondata (/var/task/node_modules/readable-stream/lib/_stream_readable.js:572:20)",
        "    at Encoder.emit (events.js:400:28)",
        "    at Encoder.emit (domain.js:475:12)",
        "    at readableAddChunk (/var/task/node_modules/readable-stream/lib/_stream_readable.js:195:16)",
        "    at Encoder.Readable.push (/var/task/node_modules/readable-stream/lib/_stream_readable.js:162:10)",
        "    at Encoder.Transform.push (/var/task/node_modules/readable-stream/lib/_stream_transform.js:145:32)",
        "    at cb (/var/task/node_modules/@suldashi/lame/lib/encoder.js:234:12)"
    ]
}

**Comment by scofield8610** [comment]
And this one:

"type": "SessionEndedRequest",
"requestId": "amzn1.echo-api.request.340c52af-752c-4bbe-b50b-844654f47bce",
"timestamp": "2021-12-22T08:23:13Z",
"locale": "de-DE",
"reason": "ERROR",
"error": {
"type": "INVALID_RESPONSE",
"message": "An exception occurred while dispatching the request to the skill."

**Comment by jsetton** [comment]
> now all functions works fine, thank you again!

Awesome! If you experienced the "ERR_STREAM_WRITE_AFTER_END" error again, please provide the full Lambda logs of the relevant request that triggered the exception. There might be a race condition event that needs to be handled.

**Comment by scofield8610** [comment]
allright I will report

**Comment by jsetton** [comment]
I made some changes around improving the handling of stream errors and possibility fixed the relevant race condition. You should update your skill to the latest version. You should know the drill by now 😄
