### ISSUE TITLE
TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by satishgadhave** [tartanguru/alexa-assistant#30]
I got this error in lambda function (copied from cloudwatch logs)
What should I do?

2017-11-07T19:58:34.237Z	08175f85-c3f6-11e7-a35b-7d9be49e6c0b	TypeError: Cannot read property 'locale' of undefined
at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:103:38)
at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:92:31)
at exports.handler (/var/task/index.js:803:11)

**Comment by tartanguru** [comment]
This error is caused by uploading the wrong zip file - make sure you are
uploading index.zip and not the zip you downloaded from github

**Comment by satishgadhave** [comment]
I traced further and found that Zip file uploaded is correct and response generated is saved in S3 bucket as a audio file.
Problem is while retrieving the file from bucket throws error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2017-11-08T18:08:11Z</Expires>
<ServerTime>2017-11-08T18:08:51Z</ServerTime>
<RequestId>834C0B6B8EB1F46B</RequestId>
<HostId>
GGnjObHtOzz6qaLMzOampoKzvm419/4OmhdttCxRjO7dCrXVGcm9o/o7pVbQHuWqKoRZOZ5jHI8=
</HostId>
</Error>
```
