### ISSUE TITLE
NodeJS 6.1.0 Deprecation in AWS

### ISSUE THREAD

**Issue by photinus** [tartanguru/alexa-assistant#81]
Got notified today that Amazon is deprecating NodeJS 6.1 support, Do you know if a newer version of NodeJS will work in AWS for this?

**Comment by photinus** [comment]
Looks like just updating it to NodeJS 8.1 wont work:

module initialization error: Error
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
at Object.Module._extensions..node (module.js:681:18)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)
at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:99)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)

**Comment by dextersgenius** [comment]
@tartanguru Any updates on this please?

**Comment by dwl99** [comment]
nothing?

**Comment by tartanguru** [comment]
This isn't a trivial piece of work to do as it involves rebuilding the
skill against the latest version of node.js, testing the build, rebuilding
the distribution package, deploying a new zip to S3 and then updating the
cloudformation template.
My current workload doesn't allow me time to do this at the moment

Sorry

**Comment by shackrock** [comment]
With this going EOL, will this fail to function anymore?  What is everyone doing instead?

**Comment by tartanguru** [comment]
Existing installations should continue working.

**Comment by TPISCAREL** [comment]
The fresh installation from the instruction is no longer work right?

**Comment by nilava** [comment]
@tartanguru hey it would be really great if you get time to update it to latest version 👍

**Comment by hlfritz** [comment]
i WAS able to edit the template and change that portion of the code to nodejs8.10 (in a new window to edit the template while i deleted the failed skill in the original window) and successfully create the skill, but i have a problem with it - "There was a problem with the requested skills response".

i tried looking for the solution shown in troubleshooting but the amazon interface has changed again and there is no render template option that i can find. i am not sure if my issue is related to the nodejs change in the template or i missed something.

willing to help test.

**Comment by vret123** [comment]
@tartanguru same issue as the others..change part of the code to use node.js8.10 (also tried 10.x)..seems to proceed (because if I use the now deprecated node.js6.1.0, it returns ROLLBACK_STARTED ROLLBACK_REQUESTED ROLLBACK_COMPLETED CREATE_FAILED) but returns "There was a problem with the requested skills response"..Amazon's UI changed again and can't find render template.. help?

**Comment by Skyleiger** [comment]
Yeah, I also have changes the version in the cloudformation.json to node8.10 and Alexa now also returns "There was a problem with the requested skills response.".
Is there any solution right now?

**Comment by Skyleiger** [comment]
Because AWS isn't supporting node6.10 anymore.

**Comment by vret123** [comment]
@tartanguru update pls

**Comment by photinus** [comment]
The skill as a whole would need to be re-built around Node 8.10, I tried a few times in a dev environment and some of the dependencies are unhappy as well in Node 8.10 (which tends to be where I get stuck).

@tartanguru already responded to this here: https://github.com/tartanguru/alexa-assistant/issues/81#issuecomment-485790873

**Comment by kishorenagaraj** [comment]
I was able to get it running by building the code in an EC2 amazon linux 1 instance after installing nodejs 8.10 on it, zipping it and uploading it to lambda stack. The cloudformation template has to be modified to runtime 8.10.

**Comment by vijayrad** [comment]
Thanks for the update. Can you please provide step by step instructions on the steps you followed

**Comment by photinus** [comment]
> I was able to get it running by building the code in an EC2 amazon linux 1 instance after installing nodejs 8.10 on it, zipping it and uploading it to lambda stack. The cloudformation template has to be modified to runtime 8.10.

Do you have a link to an updated repo or cloudformation url?

**Comment by kishorenagaraj** [comment]
I am rather very new to aws/nodejs, i have made only one change using the template designer to the template other than changing the nodejs6.10 to nodejs8.10.
Also, no changes to the repo other than compiling it. I could provide the compiled index.zip file which you can then upload to the function stack.

**Comment by vijayrad** [comment]
Hi Kishore,

It will be good if you can share the index.,zip file and how you uploaded
it to AWS

**Comment by kishorenagaraj** [comment]
Here is a quick steps I could come up with:
https://github.com/kishorenagaraj/alexa-assistant/wiki/An-attempt-to-solve-nodejs6.10-runtime-issue

@tartanguru , please let me know if you do not like this steps/approach, I will take it down.

**Comment by vijayrad** [comment]
Thanks a lot for the guide Kishore. It works like a charm for me. Really appreciate it..

**Comment by Skyleiger** [comment]
Yeah, thanks. It worked also for me.

**Comment by tiger-tw** [comment]
Many thanks for this workaround. Tried it a few days ago and it is working now.
Just recieved a mail today, that node8.1 will be deprecated at the end of the year. Hope it will be functunal after Feb 2020 ;-)

**Comment by taribo** [comment]
Ciao @kishorenagaraj I tried to follow your instruction but when I try to connect the skill to my account I receive a "is not possible link the Skill Google Assistant for Alexa. "

Any ideas?

thank you

**Comment by taribo** [comment]
how can change the default language to italian?

**Comment by taribo** [comment]
is it possible use youtube?

**Comment by jane-t** [comment]
> 
> 
> Here is a quick steps I could come up with:
> https://github.com/kishorenagaraj/alexa-assistant/wiki/An-attempt-to-solve-nodejs6.10-runtime-issue
> 
> @tartanguru , please let me know if you do not like this steps/approach, I will take it down.

This worked for me.   I had to tinker a bit with the intents and ended up with 
Ask _Google to_ search for **{search}**

**Comment by simon6162** [comment]
> Here is a quick steps I could come up with:
> https://github.com/kishorenagaraj/alexa-assistant/wiki/An-attempt-to-solve-nodejs6.10-runtime-issue
> 
> @tartanguru , please let me know if you do not like this steps/approach, I will take it down.

This is now also not working as Node 8 is not allowed for new stacks (same rollback error). I had to change the json in step 2 to 
"Runtime": "nodejs12.x",

Then it can be switched back to node 8 when updating the zip file in step 5.

Thanks for the amazing work, its all running for me with a  fresh setup in Jan 2020.

**Comment by Evilknavel** [comment]
> > Here is a quick steps I could come up with:
> > https://github.com/kishorenagaraj/alexa-assistant/wiki/An-attempt-to-solve-nodejs6.10-runtime-issue
> > @tartanguru , please let me know if you do not like this steps/approach, I will take it down.
> 
> This is now also not working as Node 8 is not allowed for new stacks (same rollback error). I had to change the json in step 2 to
> "Runtime": "nodejs12.x",
> 
> Then it can be switched back to node 8 when updating the zip file in step 5.
> 
> Thanks for the amazing work, its all running for me with a fresh setup in Jan 2020.

I second this, confirmed running fine with this workaround. Thanks for the updates, though ths was a lost cause.

**Comment by johntobin** [comment]
> > > Here is a quick steps I could come up with:
> > > https://github.com/kishorenagaraj/alexa-assistant/wiki/An-attempt-to-solve-nodejs6.10-runtime-issue
> > > @tartanguru , please let me know if you do not like this steps/approach, I will take it down.
> > 
> > 
> > This is now also not working as Node 8 is not allowed for new stacks (same rollback error). I had to change the json in step 2 to
> > "Runtime": "nodejs12.x",
> > Then it can be switched back to node 8 when updating the zip file in step 5.
> > Thanks for the amazing work, its all running for me with a fresh setup in Jan 2020.
> 
> I second this, confirmed running fine with this workaround. Thanks for the updates, thought this was a lost cause.

Also worked for me too. Not much time left to 'switch back' to nodejs8 though, the new deprecation date is Feb 3rd 2020 I think, not sure what happens after that (presumably this new zip won't work with nodejs12?). 

Thanks for getting it working @kishorenagaraj !

**Comment by blak24** [comment]
Hello everyone. I'm looking for a solution in using the skill with another version of Nodejs. I read latest comments here but didn't understand too much. I mean, it seems also Nodejs8 is deprecated now, so the possible solution posted here doesn't work anymore again? What should I do? Consider I'm doing a fresh installation. Thanks everyone!

**Comment by 007hiho007** [comment]
would be good for me too if someone can update any tutorial... not working for me either

**Comment by HeyboyOne** [comment]
Hello, 
I´m very new here and in this topic. 
I really like to install the Google Assistant Skill in Alexa. 
could someone explain me or give me an instruction how to install now.
I do everything till AWS because there, i get the "Rollback" Error. 
Thank you very much

**Comment by rokmohar** [comment]
I think your issue is related to this: https://github.com/tartanguru/alexa-assistant/issues/95

You can follow instructions from my comments.

**Comment by moberhuber** [comment]
Confirmed, following https://github.com/tartanguru/alexa-assistant/issues/95 worked for me. You need to set nodejs10.x as the runtime, and then upload the lambda_1.0.zip from https://github.com/tartanguru/alexa-assistant/issues/95 .
