### ISSUE TITLE
"Skill response was marked as failure"

### ISSUE THREAD

**Issue by alfredo-rlabs** [tartanguru/alexa-assistant#87]
Got this message when trying to use the skill.
"Skill response was marked as failure

Requested Identifier: [identifier]

The target Lambda application returned a failure response.

**Comment by alfredo-rlabs** [comment]
It's something related with node JS

`
20:47:40
START RequestId: 1f5a7234-0cb0-441e-a028-9207910441a1 Version: $LATEST

20:47:40
module initialization error: Error was compiled against a different Node.js version using NODE_MODULE_VERSION 48. This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`). at Object.Module._extensions..node (module.js:681:18) at Module.load (module.js:565:32) at tryModuleLoad (modul

20:47:40
END RequestId: 1f5a7234-0cb0-441e-a028-9207910441a1

20:47:40
REPORT RequestId: 1f5a7234-0cb0-441e-a028-9207910441a1	Duration: 72.31 ms	Billed Duration: 100 ms Memory Size: 1344 MB	Max Memory Used: 95 MB

20:47:40
module initialization error Error

20:47:41
START RequestId: eee6fa3a-8230-4be9-96c2-4ae84e8b5d49 Version: $LATEST

20:47:41
module initialization error: Error was compiled against a different Node.js version using NODE_MODULE_VERSION 48. This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`). at Object.Module._extensions..node (module.js:681:18) at Module.load (module.js:565:32) at tryModuleLoad (modul

20:47:41
END RequestId: eee6fa3a-8230-4be9-96c2-4ae84e8b5d49

20:47:41
REPORT RequestId: eee6fa3a-8230-4be9-96c2-4ae84e8b5d49	Duration: 72.54 ms	Billed Duration: 100 ms Memory Size: 1344 MB	Max Memory Used: 56 MB

20:47:41
module initialization error Error`

**Comment by rokmohar** [comment]
I think your issue is related to this: https://github.com/tartanguru/alexa-assistant/issues/95

You can follow instructions from my comments.
