### ISSUE TITLE
Cant load skill because of failure lambda

### ISSUE THREAD

**Issue by 007hiho007** [tartanguru/alexa-assistant#91]
Hi,

When i load google on my alexa i got an error.

Attached a picture... does anyone knows how to solve it ?
![20200222_112059](https://user-images.githubusercontent.com/61327246/75090691-c0078e80-5565-11ea-8932-e1e5d74c82cf.jpg)

**Comment by rokmohar** [comment]
I think your issue is related to this: https://github.com/tartanguru/alexa-assistant/issues/95

**Comment by michaelsage** [comment]
Hi, 
I have followed the instructions and the comments in #95 , but I have the same issue, log below...
Runtime.HandlerNotFound

2020-06-30T09:15:23.426+01:00 | 2020-06-30T08:15:23.424Z	undefined	ERROR	Uncaught Exception	{     "errorType": "Runtime.HandlerNotFound",     "errorMessage": "index.handler is undefined or not exported",     "stack": [         "Runtime.HandlerNotFound: index.handler is undefined or not exported",         "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",         "    at Object.<anonymous> (/var/runtime/index.js:45:30)",         "    at Module._compile (internal/modules/cjs/loader.js:778:30)",         "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",         "    at Module.load (internal/modules/cjs/loader.js:653:32)",         "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",         "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",         "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",         "    at startup (internal/bootstrap/node.js:283:19)",         "    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"     ] }
-- | --

**Comment by michaelsage** [comment]
Ok, just realised the zip hadn't uploaded properly. Reloaded the zip found in #95 and the problem has gone away, leaving this error and comment here in case someone has the same issue.

**Comment by rokmohar** [comment]
AWS Lambda will drop support for Node 10.x, I've upgraded the code to compile for Node 12.x, you should download v1.1 instead.
