### ISSUE TITLE
Not supported nodejs version

### ISSUE THREAD

**Issue by Susja** [tartanguru/alexa-assistant#92]
Hello.
I'm actually not a web developer and following tutorial written by someone in order to create Google Assistant Skill for Alexa.
At the step to create a stack it failed with the following error:
The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 9623824b-f2d8-4880-837c-463782d4eac4)
Could someone explain how to change nodejs runtime?
If possible I'd prefer to do it by changing some setting rather than coding because I'm not familiar with web services.
Thanks a lot

**Comment by Susja** [comment]
Hi,
I was able to change the version in local template and than complete the process successfully.
Unfortunately it does not work for me. It throws this error when I invoke it:
--
a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).","stack":["Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'","was compiled against a different Node.js version using","NODE_MODULE_VERSION 48. This version of Node.js requires","NODE_MODULE_VERSION 72. Please try re-compiling or re-installing","the module (for instance, using `npm rebuild` or `npm install`).","    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)","    at Module.load (internal/modules/cjs/loader.js:1002:32)","    at Function.Module._load (internal/modules/cjs/loader.js:901:14)","    at Module.require (internal/modules/cjs/loader.js:1044:19)","    at require (internal/modules/cjs/helpers.js:77:18)","    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)","    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)","    at Module._compile (internal/modules/cjs/loader.js:1158:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)","    at Module.load (internal/modules/cjs/loader.js:1002:32)"]}
2020-04-01T18:56:23.306Z	undefined	INFO	Uncaught exception: Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
/var/task/node_modules/alexa-sdk/lib/alexa.js:300
    throw err;
    ^

Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
END RequestId: 56fbf218-2bd2-440e-9b90-3b6ffed32af2
REPORT RequestId: 56fbf218-2bd2-440e-9b90-3b6ffed32af2	Duration: 560.79 ms	Billed Duration: 600 ms	Memory Size: 1344 MB	Max Memory Used: 36 MB	
RequestId: 56fbf218-2bd2-440e-9b90-3b6ffed32af2 Error: Runtime exited with error: exit status 7
Runtime.ExitError
--
Could you please help with it?
Thanks
