### ISSUE TITLE
node.js issue

### ISSUE THREAD

**Issue by Susja** [tartanguru/alexa-assistant#93]
Hello,
I was able to build it but it does not work for me.
I've got this error:
--
a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 72. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).","stack":["Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'","was compiled against a different Node.js version using","NODE_MODULE_VERSION 48. This version of Node.js requires","NODE_MODULE_VERSION 72. Please try re-compiling or re-installing","the module (for instance, using `npm rebuild` or `npm install`).","    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)","    at Module.load (internal/modules/cjs/loader.js:1002:32)","    at Function.Module._load (internal/modules/cjs/loader.js:901:14)","    at Module.require (internal/modules/cjs/loader.js:1044:19)","    at require (internal/modules/cjs/helpers.js:77:18)","    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)","    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)","    at Module._compile (internal/modules/cjs/loader.js:1158:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)","    at Module.load (internal/modules/cjs/loader.js:1002:32)"]}
2020-04-01T18:56:23.306Z	undefined	INFO	Uncaught exception: Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
/var/task/node_modules/alexa-sdk/lib/alexa.js:300
    throw err;
    ^

Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
END RequestId: 56fbf218-2bd2-440e-9b90-3b6ffed32af2
REPORT RequestId: 56fbf218-2bd2-440e-9b90-3b6ffed32af2	Duration: 560.79 ms	Billed Duration: 600 ms	Memory Size: 1344 MB	Max Memory Used: 36 MB	
RequestId: 56fbf218-2bd2-440e-9b90-3b6ffed32af2 Error: Runtime exited with error: exit status 7
Runtime.ExitError
--
Could you help with it?
Thanks

**Comment by rokmohar** [comment]
I think your issue is related to this: https://github.com/tartanguru/alexa-assistant/issues/95

You can follow my instructions from the comments.

**Comment by snadeau89** [comment]
Hi @rokmohar :)

Could you please have a look at the following issue: https://github.com/tartanguru/alexa-assistant/issues/99

I think we are several people experiencing the same issue, so it would be soooooo kind of you to take a bit of your time to look at it!

Thank you very much in advance!

**Comment by 1liminal1** [comment]
@snadeau89 It does work, I had the same issue you're facing. Deleted everything on the Amazon side and started again. Its now working.

**Comment by moberhuber** [comment]
Confirmed, following https://github.com/tartanguru/alexa-assistant/issues/95 worked for me. You need to set Runtime to nodejs10.x and upload the lambda_1.0.zip from https://github.com/tartanguru/alexa-assistant/issues/95 .

**Comment by rokmohar** [comment]
AWS Lambda will drop support for Node 10.x, I've upgraded the code to compile for Node 12.x, you should download v1.1 instead.

**Comment by Niecs** [comment]
> AWS Lambda will drop support for Node 10.x, I've upgraded the code to compile for Node 12.x, you should download v1.1 instead.

Any link to v1.1?
