### ISSUE TITLE
The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version

### ISSUE THREAD

**Issue by hge3370** [tartanguru/alexa-assistant#98]
Hi,
I am totally new on this and tried to follow all as laid out in the different streams.
When trying to use the assistant now, it fails and this is the log:

2020-05-26T00:54:18.891Z undefined ERROR Uncaught Exception {"errorType":"Error","errorMessage":"The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 64. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).","stack":["Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'","was compiled against a different Node.js version using","NODE_MODULE_VERSION 48. This version of Node.js requires","NODE_MODULE_VERSION 64. Please try re-compiling or re-installing","the module (for instance, using `npm rebuild` or `npm install`)."," at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)"," at Module.load (internal/modules/cjs/loader.js:653:32)"," at tryModuleLoad (internal/modules/cjs/loader.js:593:12)"," at Function.Module._load (internal/modules/cjs/loader.js:585:3)"," at Module.require (internal/modules/cjs/loader.js:692:17)"," at require (internal/modules/cjs/helpers.js:25:18)"," at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)"," at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)"," at Module._compile (internal/modules/cjs/loader.js:778:30)"," at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)"]}

2020-05-26T02:54:18.897+02:00
2020-05-26T00:54:18.897Z undefined INFO Uncaught exception: Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Error: The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
 at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
 at Module.load (internal/modules/cjs/loader.js:653:32)
 at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
 at Function.Module._load (internal/modules/cjs/loader.js:585:3)
 at Module.require (internal/modules/cjs/loader.js:692:17)
 at require (internal/modules/cjs/helpers.js:25:18)
 at bindings (/var/task/lib/node_modules/lame/node_modules/bindings/bindings.js:76:44)
 at Object.<anonymous> (/var/task/lib/node_modules/lame/lib/bindings.js:1:37)
 at Module._compile (internal/modules/cjs/loader.js:778:30)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

2020-05-26T02:54:18.897+02:00
/var/task/node_modules/alexa-sdk/lib/alexa.js:300

2020-05-26T02:54:18.897+02:00
throw err;

2020-05-26T02:54:18.897+02:00
^

I have no clue what is wrong, tried redoing all several times, but still the same error.  The necessary files were updated to use the 10.x version (verified in the editor) and the compile has also been done against the correct version.

What can you suggest? Much appreciated.

Hugo

**Comment by moberhuber** [comment]
You need to upload the new lambda_1.0.zip from https://github.com/tartanguru/alexa-assistant/issues/95 -- this worked for me.

**Comment by rokmohar** [comment]
AWS Lambda will drop support for Node 10.x, I've upgraded the code to compile for Node 12.x, you should download v1.1 instead.

**Comment by hge3370** [comment]
Thank you very much for the heads up. 
Much appreciated. 
Hugo 


Van: "Rok Mohar" ***@***.***> 
Aan: "tartanguru/alexa-assistant" ***@***.***> 
Cc: "hugo" ***@***.***>, "Author" ***@***.***> 
Verzonden: Donderdag 3 juni 2021 13:28:07 
Onderwerp: Re: [tartanguru/alexa-assistant] The module '/var/task/lib/node_modules/lame/build/Release/bindings.node'\nwas compiled against a different Node.js version (#98) 





AWS Lambda will drop support for Node 10.x, I've upgraded the code to compile for Node 12.x, you should download v1.1 instead.
